version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p3ssw0rd
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    #healthcheck:
      #test: [ "CMD-SHELL", "pg_isready" ]
      #interval: 1s
      #timeout: 5s
      #retries: 10

volumes:
  pgdata:
